### ISSUE TITLE
开源骗人？好歹维护一下啊 笑死了  不然不要写开源奥

### ISSUE THREAD

**Issue by brook-w** [zstackio/zstack-dashboard#138]

**Comment by brook-w** [comment]
六年前的提交！！！

**Comment by MatheMatrix** [comment]
ZStack 的开源策略目前是开放核心代码（ https://github.com/zstackio/zstack ），目前新版本的前端代码不在开放部分哦

**Comment by QiRaining** [comment]
https://github.com/zstackio/zstack-dashboard 代码已经写完了，稳定运行，所以不需要变动哈。
